CREATE TABLE IF NOT EXISTS checked_tasks (
    sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    checked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (sha256)
);
